import deepFreeze from "../utils/deepFreeze";

// Portraits retrieved from "Dialogue res/Cuadros"

const ALL_PORTRAITS = [
	// #region Oliver Valdivia
	{
		label: "Oliver Beebo (House of Vera/Purple)",
		options: {
			"oliver/house/angy.png": "Beebo > Angry",
			"oliver/house/hatangy.png": "Beebo > Angry (no hat)",
			"oliver/house/annoy.png": "Beebo > Annoyed",
			"oliver/house/hatannoy.png": "Beebo > Annoyed (no hat)",
			"oliver/house/hataw.png": "Beebo > Aw (no hat)",
			"oliver/house/bleed.png": "Beebo > Bleeding",
			"oliver/house/hatbleed.png": "Beebo > Bleeding (no hat)",
			"oliver/house/confused.png": "Beebo > Confused",
			"oliver/house/hatconfused.png": "Beebo > Confused (no hat)",
			"oliver/house/cry.png": "Beebo > Crying",
			"oliver/house/hatcry.png": "Beebo > Crying (no hat)",
			"oliver/house/down.png": "Beebo > Down",
			"oliver/house/hatdown.png": "Beebo > Down (no hat)",
			"oliver/house/verg.png": "Beebo > Embarrassed",
			"oliver/house/excited.png": "Beebo > Excited",
			"oliver/house/hatexcited.png": "Beebo > Excited (no hat)",
			"oliver/house/glad.png": "Beebo > Glad",
			"oliver/house/hatglad.png": "Beebo > Glad (no hat)",
			"oliver/house/happy.png": "Beebo > Happy",
			"oliver/house/hathappy.png": "Beebo > Happy (no hat)",
			"oliver/house/happybleed.png": "Beebo > Happy & bleeding",
			"oliver/house/hathappybleed.png": "Beebo > Happy & bleeding (no hat)",
			"oliver/house/hehe.png": "Beebo > Hehe",
			"oliver/house/hathehe.png": "Beebo > Hehe (no hat)",
			"oliver/house/judgy.png": "Beebo > Judgy",
			"oliver/house/hatjudgy.png": "Beebo > Judgy (no hat)",
			"oliver/house/side.png": "Beebo > Looking to side",
			"oliver/house/hatside.png": "Beebo > Looking to side (no hat)",
			"oliver/house/sideodd.png": "Beebo > Looking to side, odd",
			"oliver/house/hatsideodd.png": "Beebo > Looking to side, odd (no hat)",
			"oliver/house/neutro.png": "Beebo > Neutral",
			"oliver/house/hatneutro.png": "Beebo > Neutral (no hat)",
			"oliver/house/odd.png": "Beebo > Odd",
			"oliver/house/hatodd.png": "Beebo > Odd (no hat)",
			"oliver/house/question.png": "Beebo > Questioning",
			"oliver/house/hatquestion.png": "Beebo > Questioning (no hat)",
			"oliver/house/red.png": "Beebo > Red",
			"oliver/house/hatred.png": "Beebo > Red (no hat)",
			"oliver/house/scared.png": "Beebo > Scared",
			"oliver/house/hatscared.png": "Beebo > Scared (no hat)",
			"oliver/house/shadow.png": "Beebo > Shadow",
			"oliver/house/hatshadow.png": "Beebo > Shadow (no hat)",
			"oliver/house/sillyangy.png": "Beebo > Silly-angry",
			"oliver/house/smug.png": "Beebo > Smug",
			"oliver/house/hatsmug.png": "Beebo > Smug (no hat)",
			"oliver/house/speak.png": "Beebo > Speaking",
			"oliver/house/hatspeak.png": "Beebo > Speaking (no hat)",
			"oliver/house/sorpr.png": "Beebo > Surprised",
			"oliver/house/hatsurp.png": "Beebo > Surprised (no hat)",
			"oliver/house/midsurp.png": "Beebo > Mildly surprised",
			"oliver/house/hatmidsurp.png": "Beebo > Mildly surprised (no hat)",
			"oliver/house/sweet.png": "Beebo > Sweet",
			"oliver/house/hatsweet.png": "Beebo > Sweet (no hat)",
			"oliver/house/uneasy.png": "Beebo > Uneasy",
			"oliver/house/hatuneasy.png": "Beebo > Uneasy (no hat)",
			"oliver/house/worry.png": "Beebo > Worried",
			"oliver/house/hatworry.png": "Beebo > Worried (no hat)",
		},
	},
	{
		label: "Oliver Beebo (Present/Orange)",
		options: {
			"oliver/color/annoy.png": "Beebo > Annoyed",
			"oliver/color/confused.png": "Beebo > Confused",
			"oliver/color/down.png": "Beebo > Down",
			"oliver/color/verg.png": "Beebo > Embarrassed",
			"oliver/color/excited.png": "Beebo > Excited",
			"oliver/color/glad.png": "Beebo > Glad",
			"oliver/color/happy.png": "Beebo > Happy",
			"oliver/color/hehe.png": "Beebo > Hehe",
			"oliver/color/judgy.png": "Beebo > Judgy",
			"oliver/color/side.png": "Beebo > Looking to side",
			"oliver/color/sideodd.png": "Beebo > Looking to side, odd",
			"oliver/color/neutro.png": "Beebo > Neutral",
			"oliver/color/odd.png": "Beebo > Odd",
			"oliver/color/question.png": "Beebo > Questioning",
			"oliver/color/red.png": "Beebo > Red",
			"oliver/color/shadow.png": "Beebo > Shadow",
			"oliver/color/sorpr.png": "Beebo > Surprised",
			"oliver/color/midsurp.png": "Beebo > Mildly surprised",
			"oliver/color/sweet.png": "Beebo > Sweet",
			"oliver/color/worry.png": "Beebo > Worried",
		},
	},
	{
		label: "Oliver Beebo (Gallery era/Yellow)",
		options: {
			"oliver/galleryin/angy.png": "Beebo > Angry",
			"oliver/galleryin/annoy.png": "Beebo > Annoyed",
			"oliver/galleryin/verg.png": "Beebo > Crying",
			"oliver/galleryin/down.png": "Beebo > Down",
			"oliver/galleryin/happy.png": "Beebo > Happy",
			"oliver/galleryin/judgy.png": "Beebo > Judgy",
			"oliver/galleryin/side.png": "Beebo > Looking to side",
			"oliver/galleryin/sideodd.png": "Beebo > Looking to side, odd",
			"oliver/galleryin/neutro.png": "Beebo > Neutral",
			"oliver/galleryin/odd.png": "Beebo > Odd",
			"oliver/galleryin/question.png": "Beebo > Questioning",
			"oliver/galleryin/scared.png": "Beebo > Scared",
			"oliver/galleryin/shadow.png": "Beebo > Shadow",
			"oliver/galleryin/sorpr.png": "Beebo > Surprised",
			"oliver/galleryin/midsurp.png": "Beebo > Mildly surprised",
			"oliver/galleryin/speak.png": "Beebo > Speaking",
			"oliver/galleryin/uneasy.png": "Beebo > Uneasy",
			"oliver/galleryin/worry.png": "Beebo > Worried",
		},
	},
	{
		label: "Oliver Beebo (Gallery era/Orange)",
		options: {
			"oliver/galleryout/verg.png": "Beebo > Crying",
			"oliver/galleryout/down.png": "Beebo > Down",
			"oliver/galleryout/scared.png": "Beebo > Scared",
			"oliver/galleryout/shadow.png": "Beebo > Shadow",
			"oliver/galleryout/sorpr.png": "Beebo > Surprised",
			"oliver/galleryout/speak.png": "Beebo > Speaking",
			"oliver/galleryout/worry.png": "Beebo > Worried",
		},
	},
	{
		label: "Oliver Beebo (Young)",
		options: {
			"oliver/young/angy.png": "Beebo > Angry",
			"oliver/young/annoy.png": "Beebo > Annoyed",
			"oliver/young/happy.png": "Beebo > Happy",
			"oliver/young/hehe.png": "Beebo > Hehe",
			"oliver/young/judge.png": "Beebo > Judgy",
			"oliver/young/side.png": "Beebo > Looking to side",
			"oliver/young/neutro.png": "Beebo > Neutral",
			"oliver/young/odd.png": "Beebo > Odd",
			"oliver/young/question.png": "Beebo > Questioning",
			"oliver/young/surp.png": "Beebo > Surprised",
			"oliver/young/midsurp.png": "Beebo > Mildly surprised",
			"oliver/young/think.png": "Beebo > Thinking",
			"oliver/young/tired.png": "Beebo > Tired",
			"oliver/young/worry.png": "Beebo > Worried",
		},
	},
	// #endregion

	// #region Ángel Valdivia
	{
		label: "Ángel Valdivia (House of Vera/Purple)",
		options: {
			"angel/house/bigangy.png": "Ángel > Very angry",
			"angel/house/hatbigangy.png": "Ángel > Very angry (with hat)",
			"angel/house/browraise.png": "Ángel > Brow raised",
			"angel/house/hatbrowraise.png": "Ángel > Brow raised (with hat)",
			"angel/house/confused.png": "Ángel > Confused",
			"angel/house/hatconfused.png": "Ángel > Confused (with hat)",
			"angel/house/down.png": "Ángel > Down",
			"angel/house/hatdown.png": "Ángel > Down (with hat)",
			"angel/house/glad.png": "Ángel > Glad",
			"angel/house/hatglad.png": "Ángel > Glad (with hat)",
			"angel/house/haha.png": "Ángel > Haha",
			"angel/house/hathaha.png": "Ángel > Haha (with hat)",
			"angel/house/happy.png": "Ángel > Happy",
			"angel/house/hathappy.png": "Ángel > Happy (with hat)",
			"angel/house/hehe.png": "Ángel > Hehe",
			"angel/house/hathehe.png": "Ángel > Hehe (with hat)",
			"angel/house/hmph.png": "Ángel > Hmph",
			"angel/house/hathmph.png": "Ángel > Hmph (with hat)",
			"angel/house/side.png": "Ángel > Looking to side",
			"angel/house/hatside.png": "Ángel > Looking to side (with hat)",
			"angel/house/side2.png": "Ángel > Looking to side 2",
			"angel/house/hatside2.png": "Ángel > Looking to side 2 (with hat)",
			"angel/house/neutro.png": "Ángel > Neutral",
			"angel/house/hatneutro.png": "Ángel > Neutral (with hat)",
			"angel/house/odd.png": "Ángel > Odd",
			"angel/house/hatodd.png": "Ángel > Odd (with hat)",
			"angel/house/red.png": "Ángel > Red",
			"angel/house/hatred.png": "Ángel > Red (with hat)",
			"angel/house/sad.png": "Ángel > Sad",
			"angel/house/hatsad.png": "Ángel > Sad (with hat)",
			"angel/house/sadsmile.png": "Ángel > Sadly smiling",
			"angel/house/hatsadsmile.png": "Ángel > Sadly smiling (with hat)",
			"angel/house/sadspeak.png": "Ángel > Sadly speaking",
			"angel/house/hatsadspeak.png": "Ángel > Sadly speaking (with hat)",
			"angel/house/scarf.png": "Ángel > Scarf",
			"angel/house/kill.png": "Ángel > Silhouette",
			"angel/house/smile.png": "Ángel > Smiling",
			"angel/house/hatsmile.png": "Ángel > Smiling (with hat)",
			"angel/house/smiling.png": "Ángel > Smiling, talking",
			"angel/house/hatsmiling.png": "Ángel > Smiling, talking (with hat)",
			"angel/house/speak.png": "Ángel > Speaking",
			"angel/house/hatspeak.png": "Ángel > Speaking (with hat)",
			"angel/house/surprised.png": "Ángel > Surprised",
			"angel/house/hatsurprised.png": "Ángel > Surprised (with hat)",
			"angel/house/think.png": "Ángel > Thinking",
			"angel/house/hatthink.png": "Ángel > Thinking (with hat)",
			"angel/house/deepthink.png": "Ángel > Thinking deeply",
			"angel/house/hatdeepthink.png": "Ángel > Thinking deeply (with hat)",
			"angel/house/bigworry.png": "Ángel > Very worried",
			"angel/house/hatbigworry.png": "Ángel > Very worried (with hat)",
		},
	},
	{
		label: "Ángel Valdivia (Gray)",
		options: {
			"angel/color/browraise.png": "Ángel > Brow raised",
			"angel/color/confused.png": "Ángel > Confused",
			"angel/color/down.png": "Ángel > Down",
			"angel/color/glad.png": "Ángel > Glad",
			"angel/color/happy.png": "Ángel > Happy",
			"angel/color/hehe.png": "Ángel > Hehe",
			"angel/color/hmph.png": "Ángel > Hmph",
			"angel/color/side.png": "Ángel > Looking to side",
			"angel/color/side2.png": "Ángel > Looking to side 2",
			"angel/color/neutro.png": "Ángel > Neutral",
			"angel/color/odd.png": "Ángel > Odd",
			"angel/color/sad.png": "Ángel > Sad",
			"angel/color/sadsmile.png": "Ángel > Sadly smiling",
			"angel/color/smile.png": "Ángel > Smiling",
			"angel/color/smiling.png": "Ángel > Smiling, talking",
			"angel/color/speak.png": "Ángel > Speaking",
			"angel/color/think.png": "Ángel > Thinking",
			"angel/color/bigworry.png": "Ángel > Very worried",
			"angel/color/dominion_neutro.png": "Dominion > Neutral",
		},
	},
	// #endregion

	// #region Vivi Villalobos
	{
		label: "Vivi Villalobos (House of Vera/Purple)",
		options: {
			"vivi/house/angy.png": "Vivi > Angry",
			"vivi/house/down.png": "Vivi > Down",
			"vivi/house/excited.png": "Vivi > Excited",
			"vivi/house/happy.png": "Vivi > Happy",
			"vivi/house/hehe.png": "Vivi > Hehe",
			"vivi/house/side.png": "Vivi > Looking to side",
			"vivi/house/mischief.png": "Vivi > Mischievous",
			"vivi/house/neutro.png": "Vivi > Neutral",
			"vivi/house/pout.png": "Vivi > Pouting",
			"vivi/house/sad.png": "Vivi > Sad",
			"vivi/house/surprised.png": "Vivi > Surprised",
			"vivi/house/think.png": "Vivi > Thinking",
		},
	},
	{
		label: "Vivi Villalobos (Red)",
		options: {
			"vivi/color/angy.png": "Vivi > Angry",
			"vivi/color/down.png": "Vivi > Down",
			"vivi/color/excited.png": "Vivi > Excited",
			"vivi/color/happy.png": "Vivi > Happy",
			"vivi/color/hehe.png": "Vivi > Hehe",
			"vivi/color/side.png": "Vivi > Looking to side",
			"vivi/color/mischief.png": "Vivi > Mischievous",
			"vivi/color/neutro.png": "Vivi > Neutral",
			"vivi/color/think.png": "Vivi > Thinking",
		},
	},
	// #endregion

	// #region Marigold Margulis
	{
		label: "Marigold Margulis (House of Vera/Purple)",
		options: {
			"marigold/house/angy.png": "Marigold > Angry",
			"marigold/house/annoy.png": "Marigold > Annoyed",
			"marigold/house/down.png": "Marigold > Down",
			"marigold/house/eager.png": "Marigold > Eager",
			"marigold/house/excited.png": "Marigold > Excited",
			"marigold/house/glad.png": "Marigold > Glad",
			"marigold/house/happy.png": "Marigold > Happy",
			"marigold/house/hehe.png": "Marigold > Hehe",
			"marigold/house/side.png": "Marigold > Looking to side",
			"marigold/house/mischief.png": "Marigold > Mischievous",
			"marigold/house/neutro.png": "Marigold > Neutral",
			"marigold/house/nost.png": "Marigold > Nostalgic",
			"marigold/house/speak.png": "Marigold > Speaking",
			"marigold/house/surp.png": "Marigold > Surprised",
		},
	},
	{
		label: "Marigold Margulis (Blue)",
		options: {
			"marigold/color/down.png": "Marigold > Down",
			"marigold/color/happy.png": "Marigold > Happy",
			"marigold/color/side.png": "Marigold > Looking to side",
			"marigold/color/neutro.png": "Marigold > Neutral",
			"marigold/color/surp.png": "Marigold > Surprised",
		},
	},
	// #endregion

	// #region Nina Coli
	{
		label: "Nina Coli (House of Vera/Purple)",
		options: {
			"nina/house/angy.png": "Nina > Angry",
			"nina/house/annoy.png": "Nina > Annoyed",
			"nina/house/down.png": "Nina > Down",
			"nina/house/excited.png": "Nina > Excited",
			"nina/house/happy.png": "Nina > Happy",
			"nina/house/side.png": "Nina > Looking to side",
			"nina/house/neutro.png": "Nina > Neutral",
			"nina/house/nost.png": "Nina > Nostalgic",
			"nina/house/nosttalk.png": "Nina > Nostalgically speaking",
			"nina/house/sad.png": "Nina > Sad",
			"nina/house/surp.png": "Nina > Surprised",
			"nina/house/midsurp.png": "Nina > Mildly surprised",
			"nina/house/think.png": "Nina > Thinking",
			"nina/house/worry.png": "Nina > Worried",
		},
	},
	{
		label: "Nina Coli (Violet)",
		options: {
			"nina/color/excited.png": "Nina > Excited",
		},
	},
	// #endregion

	// #region Nadia Margulis
	{
		label: "Nadia Margulis (House of Vera/Purple)",
		options: {
			"nadia/house/angy.png": "Nadia > Angry",
			"nadia/house/annoy.png": "Nadia > Annoyed",
			"nadia/house/down.png": "Nadia > Down",
			"nadia/house/side.png": "Nadia > Looking to side",
			"nadia/house/neutro.png": "Nadia > Neutral",
			"nadia/house/odd.png": "Nadia > Odd",
			"nadia/house/question.png": "Nadia > Questioning",
			"nadia/house/shadow.png": "Nadia > Shadow",
			"nadia/house/midsurp.png": "Nadia > Mildly surprised",
			"nadia/house/worry.png": "Nadia > Worried",
			"nadia/house/bigworry.png": "Nadia > Very worried",
		},
	},
	{
		label: "Nadia Margulis (Pink)",
		options: {
			"nadia/color/angy.png": "Nadia > Angry",
			"nadia/color/annoy.png": "Nadia > Annoyed",
			"nadia/color/side.png": "Nadia > Looking to side",
			"nadia/color/neutro.png": "Nadia > Neutral",
			"nadia/color/odd.png": "Nadia > Odd",
			"nadia/color/question.png": "Nadia > Questioning",
			"nadia/color/midsurp.png": "Nadia > Mildly surprised",
		},
	},
	// #endregion

	// #region Simon Margulis
	{
		label: "Simon Margulis (House of Vera/Purple)",
		options: {
			"simon/house/annoy.png": "Simon > Annoyed",
			"simon/house/down.png": "Simon > Down",
			"simon/house/happy.png": "Simon > Happy",
			"simon/house/side.png": "Simon > Looking to side",
			"simon/house/neutro.png": "Simon > Neutral",
			"simon/house/odd.png": "Simon > Odd",
			"simon/house/sad.png": "Simon > Sad",
			"simon/house/sadside.png": "Simon > Sadly looking to side",
			"simon/house/smile.png": "Simon > Smiling",
			"simon/house/speak.png": "Simon > Speaking",
			"simon/house/think.png": "Simon > Thinking",
			"simon/house/worry.png": "Simon > Worried",
		},
	},
	{
		label: "Simon Margulis (Green)",
		options: {
			"simon/color/down.png": "Simon > Down",
			"simon/color/happy.png": "Simon > Happy",
			"simon/color/side.png": "Simon > Looking to side",
			"simon/color/neutro.png": "Simon > Neutral",
		},
	},
	// #endregion

	// #region Owen
	{
		label: "Owen (House of Vera/Purple)",
		options: {
			"owen/house/angy.png": "Owen > Angry",
			"owen/house/annoy.png": "Owen > Annoyed",
			"owen/house/cringe.png": "Owen > Cringe",
			"owen/house/down.png": "Owen > Down",
			"owen/house/excited.png": "Owen > Excited",
			"owen/house/happy.png": "Owen > Happy",
			"owen/house/hehe.png": "Owen > Hehe",
			"owen/house/side.png": "Owen > Looking to side",
			"owen/house/neutro.png": "Owen > Neutral",
			"owen/house/odd.png": "Owen > Odd",
			"owen/house/red.png": "Owen > Red",
			"owen/house/sad.png": "Owen > Sad",
			"owen/house/smile.png": "Owen > Smiling",
			"owen/house/speak.png": "Owen > Speaking",
			"owen/house/midsurp.png": "Owen > Mildly surprised",
			"owen/house/think.png": "Owen > Thinking",
		},
	},
	{
		label: "Owen (Purplish blue)",
		options: {
			"owen/color/happy.png": "Owen > Happy",
			"owen/color/speak.png": "Owen > Speaking",
			"owen/color/think.png": "Owen > Thinking",
		},
	},
	// #endregion

	// #region Eugene Coli
	{
		label: "Eugene Coli",
		options: {
			"eugene/angy.png": "Coli > Angry",
			"eugene/bigangy.png": "Coli > Very angry",
			"eugene/aw.png": "Coli > Aw",
			"eugene/down.png": "Coli > Down",
			"eugene/excited.png": "Coli > Excited",
			"eugene/happy.png": "Coli > Happy",
			"eugene/hehe.png": "Coli > Hehe",
			"eugene/side.png": "Coli > Looking to side",
			"eugene/side2.png": "Coli > Looking to side 2",
			"eugene/neutro.png": "Coli > Neutral",
			"eugene/nost.png": "Coli > Nostalgic",
			"eugene/bad.png": "Coli > Silhouette",
			"eugene/smile.png": "Coli > Smiling",
			"eugene/speak.png": "Coli > Speaking",
			"eugene/midsurp.png": "Coli > Mildly surprised",
			"eugene/think.png": "Coli > Thinking",
		},
	},
	// #endregion

	// #region Police
	{
		label: "Police Chief",
		options: {
			"police/chief/neutro.png": "Police Chief > Neutral",
			"police/chief/speak.png": "Police Chief > Speaking",
			"police/chief/think.png": "Police Chief > Thinking",
		},
	},
	{
		label: "Police Officer 1",
		options: {
			"police/officer1/angy.png": "Police Officer > Angry",
			"police/officer1/happy.png": "Police Officer > Happy",
		},
	},
	{
		label: "Police Officer 2",
		options: {
			"police/officer2/neutro.png": "Police Officer > Neutral",
			"police/officer2/odd.png": "Police Officer > Odd",
		},
	},
	{
		label: "Police Officer 3",
		options: {
			"police/officer3/smile.png": "Police Officer > Smiling",
			"police/officer3/think.png": "Police Officer > Thinking",
		},
	},
	// #endregion

	// #region Miscellaneous
	{
		label: "Other",
		options: {
			"misc/bartender_neutro.png": "Bartender > Neutral",
			"misc/someone_shadow.png": "Someone > Silhouette (House of Vera/Purple)",
			"misc/worker_shadow.png": "Worker > Silhouette (City/Police)",
			"misc/tutorial_blank.png": "Blank square (Tutorial)",
		},
	},
	// #endregion
];

deepFreeze(ALL_PORTRAITS);

export default ALL_PORTRAITS;